### ISSUE TITLE
This does not make sense

### ISSUE THREAD

**Issue by luismelodev** [anandundavia/thanos-js#11]
Marvel created the universe.
The universe contains planets.
Planets (sometimes) contains beings (characters).
Thanos did not cut half of the universe itself.
Thanos did not cut half of the planets itselves.
Thanos did snapped *half of the beings*.
Thanos.js is cutting half of the *files*, not the *characters* of these files.

**Comment by JulyTheMonth** [comment]
Correct me if i am wrong. 

The snap of Thanos did not cut the people in half. I can't remember to see people only losing half of their body.

Either they were blibbed or they were not.

So i argue that it makes sense to either blib all of one file or nothing.

**Comment by anandundavia** [comment]
The project is analogous to the Universe.
Project contains directories -- Universe contains Planets.
A directory has files (sometimes) -- A planet has beings (sometimes).
Thanos wiped out half of the beings of the Universe.
thanos-js wipes out half of the files from the project.

So, it makes sense!
