### ISSUE TITLE
Odds are incorrect

### ISSUE THREAD

**Issue by ashgillman** [anandundavia/thanos-js#2]
`README.md` states:

> He will wipe out about one third of your files if he snaps fingers without gauntlet. And If he has the gauntlet, he will crush about half of them.

However, the following line actually wipes out about one quarter of your files if he snaps fingers without gauntlet.

https://github.com/anandundavia/thanos-js/blob/c170118bad3f6062ad820dc2a67485d17d6f970c/lib/snap-fingers.js#L29

**Comment by anandundavia** [comment]
Ah yes, I will change the `readme.md`.

You are welcome to raise a PR if you want to :D
