### ISSUE TITLE
Will half get deleted? 

### ISSUE THREAD

**Issue by RyanMcArthur22** [anandundavia/thanos-js#5]
Probably not worth the time considering what the program does but,

It seems like just doing a random number for every file will allow less than half or more than half depending on the randomness.

Should be a check to ensure exactly half occur.

Could assign a value at random to every file and then only take the top 50%.

**Comment by jschwinger23** [comment]
Agreed, Thanos would LOVE to do it.

**Comment by anandundavia** [comment]
This has been in my bucket for so long.
Finally closing this issue. with the version `0.0.10`, exactly half of the files will get deleted.

Also,  `--with-infinity-gauntlet-glove` flag would kind of be mandatory.

**Comment by anandundavia** [comment]
Aye crap, I should have created a PR for that so that I could reference it here. Anyways, I directly pushed it to `master`
